[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
    {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif %}\
    {% if commit.remote.pr_number %} in #{{ commit.remote.pr_number }}{%- endif %}
{%- endfor %}
{% endfor %}
"""
trim = true
postprocessors = [
  { pattern = ":[a-z_]+: ", replace = "" },
  { pattern = "\\(#(\\d+)\\)", replace = "[#$1](https://github.com/Flaflo/yslv-userscript/issues/$1)" },
]

[remote.github]
owner = "Flaflo"
repo = "yslv-userscript"

[git]
conventional_commits = false
filter_unconventional = false
tag_pattern = '[0-9]+\.[0-9]+\.[0-9]+'
commit_parsers = [
  { message = "^:sparkles:", group = "<!-- 0 -->New Features" },
  { message = "^:bug:", group = "<!-- 1 -->Bug Fixes" },
  { message = "^:recycle:", group = "<!-- 2 -->Refactoring" },
  { message = "^:lipstick:", group = "<!-- 2 -->UI Changes" },
  { message = "^:zap:", group = "<!-- 3 -->Performance" },
  { message = "^:fire:", group = "<!-- 3 -->Removals" },
  { message = "^:adhesive_bandage:", group = "<!-- 1 -->Bug Fixes" },
  { message = "^:memo:", group = "<!-- 4 -->Documentation" },
  { message = "^:wrench:", group = "<!-- 5 -->Configuration" },
  { message = "^:arrow_up:", group = "<!-- 6 -->Dependencies" },
  { message = "^:green_heart:", skip = true },
  { message = "^:construction_worker:", skip = true },
  { message = "^:bookmark:", skip = true },
  { message = "^:art:", skip = true },
  { message = "^Merge", skip = true },
]
commit_preprocessors = []
